kind: pipeline
name: build
type: docker

steps:
  - name: build cloudsweeper
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/agari/cloudsweeper
      tags: latest
    when:
      event: [push, tag]
      branch: master
